# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: bionic
os:
  - linux
  # - osx
julia:
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false

# Do not build my PR twice.  Use the build on branch.
if: NOT (type == pull_request AND head_repo == tkf/JuliaCLI.jl)

before_install:
  - python3 --version
  - jlcli/jlcli.py --help
  - unset JULIA_PROJECT
  - julia -e 'using Pkg; pkg"add https://github.com/tkf/Run.jl"'
install:
  - julia -e 'using Run; Run.prepare_test()'
script:
  - julia -e 'using Run; Run.test()'
after_success:
  - julia -e 'using Run; Run.after_success_test()'
jobs:
  include:
    - stage: Documentation
      install:
        - julia -e 'using Run; Run.prepare_docs()'
      script:
        - julia -e 'using Run; Run.docs()'
      after_success: skip
